pull_request_rules:
  - name: automatic merging when label is set
    conditions:
      - label!=WIP
      - label!=waiting
      - label=ready to merge
      - label~=(Breaking|Bug|Documentation|Enhancement|Internal)
    actions:
      merge:
        method: merge
        strict: true
  - name: remove ready to merge when merged
    conditions:
      - merged
      - label=ready to merge
    actions:
      label:
        remove:
          - ready to merge
  - name: delete merged branches
    conditions:
      - merged
      - label!=WIP
    actions:
      delete_head_branch: {}
  - name: add WIP label when WIP is in title
    conditions:
      - title~=WIP
    actions:
      comment:
        message: Please remove WIP from the title. We have set the WIP Label for you instead.
      label:
        add:
          - WIP
  - name: remove "ready to merge" label when pull is not approved
    conditions:
      - "#approved-reviews-by=0"
      - label~=ready to merge
      - -merged
    actions:
      comment:
        message: The "ready to merge" label can only be set after one pull request approval
      label:
        remove:
          - ready to merge
  - name: comment notice when pull does not contain version info
    conditions:
      - -label~=(Breaking|Bug|Documentation|Enhancement|Internal)
    actions:
      comment:
        message: You must set a version label (breaking, bug, documentation, enhancement, internal) before we can merge this.
