language: node_js
node_js: "lts/*"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache: npm

jobs:
  include:
    # Deploy
    - stage: deploy
      name: NPM
      before_deploy:
        - echo -e "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc 2> /dev/null
      deploy:
        provider: script
        script:
          - "npm run lerna:publish -- --yes"
        skip_cleanup: true
        on:
          branch: master
    - script: skip
      name: GITHUB
      before_deploy:
        - echo -e "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGE_TOKEN}\nregistry=https://npm.pkg.github.com/schul-cloud" > .npmrc 2> /dev/null
      deploy:
        provider: script
        script:
          - "npm run lerna:publish -- --yes --registry https://npm.pkg.github.com"
        skip_cleanup: true
        on:
          branch: master
