language: node_js
node_js:
  - "10"
branches:
  only:
    - master
cache: npm


before_deploy:
  - echo -e "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGE_TOKEN}\nregistry=https://npm.pkg.github.com/schul-cloud" > .npmrc 2> /dev/null
deploy:
  provider: script
  script: "npm run lerna:publish -- --yes"
  skip_cleanup: true
  on:
    node: "10"
    branch: master
