name: Publish

on:
  push:
    branches:
      - master

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: setup
      run: |
        npm run setup
    - name: Publish
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
        npm run lerna:publish -- --yes
